spring:
  application:
    name: OpenAI Chat Bot
  main:
    allow-circular-references: true
  neo4j:
    uri: NEO4J_DB_URL
    authentication:
      username: NEO4J_DB_USERNAME
      password: NEO4J_DB_PASSWORD
  ai:
    openai:
      api-key: OPENAI_API_KEY
      chat:
        base-url: https://api.openai.com/v1/chat/completions
        model: gpt-3.5-turbo
        temperature: 0.0 #default 0.8
    vectorstore:
      neo4j:
        database-name: neo4j
        embedding-dimension: 1536
        distance-type: cosine
        label: Document
        embedding-property: embedding
        index-name: spring-ai-document-index
app:
  vector-store:
    chunkSize: 3000
    similarityThreshold: 0.75
    topK: 5
logging:
  level:
    root: INFO
    br.example.genai.chatbot.openai.app: DEBUG